[build]
  command = "npm run build:netlify"
  publish = "_site"
  functions = "functions"
  functionsSource = "_lambdas"


  [[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  template= "hierarchical"
